### ISSUE TITLE
'GTimeVal' is deprecated: Use 'GDateTime' instead

### ISSUE THREAD

**Issue by z3ntu** [ubports/url-dispatcher#8]
Deprecated since glib 2.62. Porting is not entirely straight forward because `timeval->tv_sec` (how GTimeVal is currently assigned in `service/url-db.c`), and GDateTime wants something like `g_date_time_new_from_unix_utc`

**Comment by UniversalSuperBox** [comment]
This has been reported on the lomiri-url-dispatcher repository as https://gitlab.com/ubports/core/lomiri-url-dispatcher/-/issues/2.
